### ISSUE TITLE
COuldn't scan EAN 13 barcode 

### ISSUE THREAD

**Issue by distabiolijze** [zxing-js/browser#106]
COuldn't scan EAN 13 barcode with this error message `No MultiFormat Readers were able to detect the code. `

Version:
```

    "@zxing/browser": "^0.1.1",
    "@zxing/library": "^0.19.1",

```

Settings

```
const hints = new Map();
const formats = [BarcodeFormat.EAN_8, BarcodeFormat.EAN_13, BarcodeFormat.UPC_A, , BarcodeFormat.UPC_EAN_EXTENSION];

hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);
hints.set(DecodeHintType.TRY_HARDER, true);

```

![image](https://user-images.githubusercontent.com/54104991/210181912-f601eeb0-d737-4f0f-b2b9-75c277c5babc.png)

**Comment by Shahrukh0396** [comment]
@distabiolijze  How did you resolve this issue??

**Comment by JoDeveloper** [comment]
> @distabiolijze How did you resolve this issue??

+1
