### ISSUE TITLE
Does @zxing/browser want to peer-depend on @zxing/library?

### ISSUE THREAD

**Issue by olleolleolle** [zxing-js/browser#130]
Hello! 👋 

Thanks for maintaining the health of this package! 🧑‍⚕️ 

I'm curious if it would be possible to say "@zxing/browser has a peer dependency on @zxing/library"?
  https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependencies

And, if set, it would offer "package tips" to people who didn't know that the two are connected.

**Comment by TheWirv** [comment]
Have you checked the [`package.json`](https://github.com/zxing-js/browser/blob/master/package.json)? This is already the case (and has been for a long time).

**Comment by olleolleolle** [comment]
You are absolutely right, https://github.com/zxing-js/browser/commit/5228f6d674d15cc4035bb26c6af111fda180799c added what I asked for, long ago. Closing!
