### ISSUE TITLE
Mime Type problem

### ISSUE THREAD

**Issue by michi927** [zxing-js/browser#15]
I have downloaded the repository by zip.
I change the name in the package.json to @zxing/browser1 because without changing that name I get this error by installing "npm i @zxing/browser"
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@zxing/browser" under a package
npm ERR! also called "@zxing/browser". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

After I change that name I get the folder node_modules with @zxing / browser in it.

So I imported it in my code like that:
       <script type="module">
            import { BrowserQRCodeReader } from '/browser-master/browser-master/node_modules/@zxing/browser';
          
            const codeReader = new BrowserQRCodeReader();

            const videoInputDevices = ZXingBrowser.BrowserCodeReader.listVideoInputDevices();

            // choose your media device (webcam, frontal camera, back camera, etc.)
            const selectedDeviceId = videoInputDevices[0].deviceId;

            console.log(`Started decode from camera with id ${selectedDeviceId}`);

            const previewElem = document.querySelector('#test-area-qr-code-webcam > video');

            // you can use the controls to stop() the scan or switchTorch() if available
            const controls = codeReader.decodeFromVideoDevice(selectedDeviceId, previewElem, (result, error, controls) => {
            // use the result and error values to choose your actions
            // you can also use controls API in this scope like the controls
            // returned from the method.
            });

            // stops scanning after 20 seconds
            setTimeout(() => controls.stop(), 20000);

And now I get this error:

Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

What can I do now?

**Comment by odahcam** [comment]
You are referencing the wrong path. Also did you downloaded this repo and created a file in it? If so I highly recomend you start a project from scratch and install this package trough NPM.

**Comment by michi927** [comment]
Ok I started a new project like you said and install the package trough NPM. But there is the same error again. 
I although chance the content type options to "nosniff" in the .htaccess file. But nothing works.
What do you mean with wrong path? I tried it with the path to @zxing/browser, @zxing/library and both don´t work.
If i reference to @zxing/browser/es2015 for example it don´t work again.

**Comment by odahcam** [comment]
Please setup an example online or at least link a repo here where the same error occours with actual data to reproduce the issue so we can effectively help.

**Comment by michi927** [comment]
So this is my workspace with the mimeproblem

[mimeproblem.zip](https://github.com/zxing-js/browser/files/5653297/mimeproblem.zip)

**Comment by odahcam** [comment]
This project only has a zipped node modules folder and a index.html that doesn't reproduce the issue. As shown bellow:

![image](https://user-images.githubusercontent.com/3942006/101384482-42fd9980-3899-11eb-8ab7-e206099ae112.png)

**Comment by michi927** [comment]
You have to start the index.html on a webserver like apache.
Then you get the error in the console

**Comment by odahcam** [comment]
That has absolutely nothing to do with the library, I think you would be better suited on StackOverflow.
