### ISSUE TITLE
How to properly unmount after getting barcode 

### ISSUE THREAD

**Issue by alanbugeja** [zxing-js/browser#17]
Thanks for the awesome library.

I'm using this to scan barcode via video stream

using listVideoInputDevices and decodeOnceFromVideoDevice, till here everything works perfectly fine and I get the barcode.

I move to next page in my web app which uses a another library to record video. I get camera is already in use exception.

After getting the barcode I am doing the following:

`const video = document.querySelector('video');
const mediaStream = video.srcObject;
const tracks = mediaStream.getTracks();
tracks.forEach((track) => {
 track.stop();
 mediaStream.removeTrack(track);
 });
codeReader.reset();`

am I missing something ?

Thanks

**Comment by alanbugeja** [comment]
Guys just in any case you encounter my issue.

Being that the stop method was not working well every time I went ahead to use native javascript methods to stop stream/video tracks.

So i am getting the video element by id, getting the media tracks from srcObject of element and foreach loop on the tracks and calling stop method on every track.

One thing on my huawei mate 10 pro calling getTracks() and then stop on each, leaves the camera in use. I had to call getVideoTracks() instead and these seems to work fine. I will post code once at home.

Cheers.

**Comment by odahcam** [comment]
Thanks for sharing that @alanbugeja !

**Comment by thisconnect** [comment]
> One thing on my huawei mate 10 pro calling getTracks() and then stop on each, leaves the camera in use. I had to call getVideoTracks() instead and these seems to work fine. I will post code once at home.

Trying to migrate from `@zxing/library` to `@zxing/browser` and no idea how to `.reset()`
using decodeOnceFromVideoElement. Would you share the code?

**Comment by alanbugeja** [comment]
> > One thing on my huawei mate 10 pro calling getTracks() and then stop on each, leaves the camera in use. I had to call getVideoTracks() instead and these seems to work fine. I will post code once at home.
> 
> Trying to migrate from `@zxing/library` to `@zxing/browser` and no idea how to `.reset()`
> using decodeOnceFromVideoElement. Would you share the code?

if you are referring to the code I used to dispose of the camera properly here you go, the video element parameter is the <video> tag :

`const disposeCamera = (videoElement: any) => {
    if (videoElement) {
      videoElement.srcObject
        .getVideoTracks()
        .forEach((track: any) => track.stop());
      return;
    }
  };`

**Comment by odahcam** [comment]
I would recommend using the `decodeFromVideoElement` which returns an object with some controls you can take, being one of them the `.stop()`, which you can call to stop the scanner. Just playing with the video element may introduce unexpected behaviors and the library may crash.
