### ISSUE TITLE
Trying to play video that is already playing.

### ISSUE THREAD

**Issue by bblanchon** [zxing-js/browser#33]
Hi,

Thank you very much for this awesome library.

I observed the following warning on Chrome 84 but not on Firefox 79:

> BrowserCodeReader.js:509 Trying to play video that is already playing.

Steps to reproduce:

* Open [one of the examples](https://zxing-js.github.io/library/examples/multi-camera/)
* Open Chrome's console
* Click "Start"
* See warning in console

Best regards,
Benoit

**Comment by odahcam** [comment]
Is this still relevant?

**Comment by bblanchon** [comment]
Yes, I still have this warning with 0.18.3

**Comment by odahcam** [comment]
Are you talking about the browser layer present in the library? That browser layer is deprecated and the current browser layer version is [v0.0.7](https://github.com/zxing-js/browser/releases/tag/v0.0.7).

**Comment by bblanchon** [comment]
I used `yarn add @zxing/library` and imported `BrowserCodeReader`; this isn't the way to go anymore?

**Comment by odahcam** [comment]
No, actually I have to update the README, I didn't see it was wrong. You should use `@zxing/browser` for the browser layer.

**Comment by mike-rambil** [comment]
I have this same issue and the camera doesn't start scanning anymore?
