### ISSUE TITLE
Accumulation of NotFoundException log

### ISSUE THREAD

**Issue by GaussNajera245** [zxing-js/browser#44]
It's not precisely an Issue but my console now is overflowing with NotFoundException error, I used to have the 0.0.5 version in which I used to handle that error but now I cannot control that console.log.
![image](https://user-images.githubusercontent.com/60408037/109070853-a63ce200-76b8-11eb-843b-01d98d4e0478.png)

**Comment by mxcd** [comment]
This is directly related to [Issue #412](https://github.com/zxing-js/library/issues/412) of the main library  
It has been fixed as of version `0.18.4` of `zxing-js/library`  

I created a Pull Request [PR #45](https://github.com/zxing-js/browser/pull/45) to fix this. Feel free to upvote or (@odahcam) to merge

**Comment by odahcam** [comment]
I'll merge it. Just to mention, you can just update the underlying library in your application yourself as a workaround.
