### ISSUE TITLE
Unclear docs regarding usage of BrowserMultiFormatCodeReader

### ISSUE THREAD

**Issue by DanielRuf** [zxing-js/browser#47]
It seems `BrowserMultiFormatCodeReader` needs a reader and does not work with the default constructor.

I try to create a multiformat reader but it seems the `@zxing/library` package is not installed even if it is referenced in the code of `@zxing/browser`.

```
	const hints = new Map();
    const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX/*, ...*/];

    hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);

    // const reader = new MultiFormatReader();

    const codeReader = new BrowserMultiFormatCodeReader(hints);
```

It looks like `@zxing/library` for ES6 (React) projects is missing as this is just a devDependency and peerDependency.

**Comment by DanielRuf** [comment]
Getting this: `BrowserMultiFormatCodeReader is not a constructor`.

Well, but there is a constructor in the code.

**Comment by DanielRuf** [comment]
It seems the class is named `BrowserMultiFormatReader`, not `BrowserMultiFormatCodeReader`.

**Comment by minusdavid** [comment]
I'm amazed that you're able to use DecodeHintType, but I'm loading via UMD and just at a loss..
