### ISSUE TITLE
BrowserQRCodeReader doesn't focus when I use rear camera

### ISSUE THREAD

**Issue by smolto** [zxing-js/browser#61]
Hi! 😋

Firstly, thanks for developing this great library. My problem is the following, I'm developing a web app that allows user to scan QR codes. 

===================================================================================
```
async function scanCode() {
    try {
      const codeReader = new BrowserQRCodeReader();

      const previewElem = document.querySelector(
        "#test-area-qr-code-webcam > video"
      );

      const controls2 = await codeReader.decodeOnceFromConstraints(
        {
          video: {
            aspectRatio: 1.7777777778,
            facingMode: 'environment',
            focusMode: 'continuous',
            frameRate: { ideal: 30, max: 60 },
            width: { min: 640, ideal: 640, max: 640 },
          },
          audio: false
        },
        previewElem
      )

      setSerialNumber(controls2.text)
    } catch (error) {
      console.log(error);
    }
 }
```

The result is this: 
![photo_2021-06-04_12-51-51](https://user-images.githubusercontent.com/37777549/120790808-b411c700-c533-11eb-96b7-bce0b5c03981.jpg)

And if I just set the following config, app uses front camera and autofocus works perfectly fine but, scan codes using front camera is quite uncomfortable. 
```
const controls2 = await codeReader.decodeOnceFromConstraints(
    {
        video: true,
        audio: false,
    },
    previewElem
)
```

**Comment by smolto** [comment]
After hours and hours, I realised that library is using wide camera and the problem is that wide camera doesn't autofocus. So I tested my app with a single rear camera device and I worked correctly.

**Comment by fydelio** [comment]
I have been playing around with library for quite some time and here is what I've learnt.

In the past it was easy. Smartphone had just two cameras. A front-facing and a back-facing. But now with mobiles becoming more sophisticated, suddenly they have multiple lenses, wide lenses and zoom
lenses. Unfortunately the browser / smartphone / library isnt always correct when choosing a default lense (I've experienced problems mostly with Samsung phones), with some lenses being unusable for close up Scanning, as they are unfocused. Basically the only solution I found is providing a dropdown to the user, where he can select his lenses (and potentially store the selection in a cookie).

**Comment by smolto** [comment]
@fydelio No one did. After creating this post and talking to a colleague we realised that this problem is because android phones have multiple rear cameras. If Google doesn't standarise this problem ... there isn't another solution that let the user choose and save user's preference.

**Comment by smolto** [comment]
@fydelio Would you mind to show me an example code of getting all cameras from a device and pass the camera selected as an argument to de reader?

**Comment by fydelio** [comment]
Yes, of course

How to display a select box with the various lenses
```
var videoSourceSelect = document.getElementById('videoSourceSelect')

BrowserCodeReader.listVideoInputDevices()
.then((videoInputDevices) => {

    if (videoInputDevices.length >= 1) {
        videoInputDevices.forEach((element) => {
            const sourceOption = document.createElement('option')
            sourceOption.text = element.label
            sourceOption.value = element.deviceId
            videoSourceSelect.appendChild(sourceOption)
        })
    }
})
```

When loading the codeReader, do as follows:
```
let device_id = var videoSourceSelect = document.getElementById('videoSourceSelect').value
const controls = await codeReader.decodeFromVideoDevice(device_id, previewElem, (result, error, controls) => {
});
```


If it helps (and not published yet): I'm trying to help improve the documentation. Here is a branch with a more enriched documentation. Have a look at it. You might get some more ideas (and maybe some feedback): https://github.com/fydelio/browser/tree/improved_documentation
